language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
# command to run tests
script: nosetests
install:
  - "pip install coveralls flake8"
  - "pip install ."

script:
  - "flake8 $(find . -iname '*.py')"
  - "nosetests --with-coverage --cover-package=yodl"

after_success:
  - "coveralls"
