language: python
python:
  - "2.6"
  - "2.7"
# command to run tests
script: nosetests
install:
  - "pip install coveralls flake8"
  - "pip install ."

script:
  - "nosetests --with-coverage --cover-package=jigglypuff"

after_success:
  - "coveralls"
