language: python
python:
  - "2.6"
  - "2.7"
# command to run tests
install:
  - "pip install coveralls flake8"
  - "pip install ."

script:
  - "nosetests --with-coverage --cover-package=jigglypuff"

after_success:
  - "coveralls"

after_script:
  - "flake8 jigglypuff || true"
  
notifications:
  irc:
    channels:
      - "chat.freenode.net#od1do7"
    on_success: change
  webhooks:
    urls:
      - http://moon.brodul.org/hubot/travis
    on_success: always
    on_failure: never
    on_start: never   