"""Initial transaction

Revision ID: 1544ab21bc21
Revises: None
Create Date: 2015-05-17 12:31:22.737860

"""

# revision identifiers, used by Alembic.
revision = '1544ab21bc21'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # XXX seems OK
    op.create_table('boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('youtube_id', sa.Text(), nullable=True),
    sa.Column('title', sa.Unicode(), nullable=True),
    sa.Column('length', sa.Unicode(), nullable=True),
    sa.Column('file_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id'),
    sa.UniqueConstraint('youtube_id')
    )
    op.create_table('boards_songs',
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], )
    )
    op.create_index('idx_board_song', 'boards_songs', ['board_id', 'song_id'], unique=False)
    op.create_index('idx_song_board', 'boards_songs', ['song_id', 'board_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_song_board', table_name='boards_songs')
    op.drop_index('idx_board_song', table_name='boards_songs')
    op.drop_table('boards_songs')
    op.drop_table('songs')
    op.drop_table('boards')
    ### end Alembic commands ###
